### ISSUE TITLE
Line-through won't work

### ISSUE THREAD

**Issue by isabelle6** [isabelle6/dsn1676-assignment-5#2]
I can't seem to get the line-through to work when I click on a list item (to mark it as complete). It works when I get rid of the display: inline-block, but then it doesn't line up with the delete button.

@thomasjbradley

**Comment by thomasjbradley** [comment]
My guess would be that if you remove the `display: inline-block` then use `position: absolute` on the button, it should solve the problem.

**Comment by isabelle6** [comment]
I tried and it made the button go below the text, and then the button would cover the text of the next list item. I tried changing display: inline-block to display: inline and that seemed to centre the button vertically with the text, but now it won't go over to the right and line up nicely. I tried putting float: right in the button, but it did this weird thing with the buttons when you make multiple list items.
![screen shot 2015-02-28 at 9 27 00 pm](https://cloud.githubusercontent.com/assets/6333962/6429205/3c42d9b6-bf91-11e4-917e-1e8566ff1f4c.png)

**Comment by thomasjbradley** [comment]
Position absolute is the only way to solve the problem. You'll need to use it plus it's top/right coordinates.

**Comment by isabelle6** [comment]
Ok, so I added in position: absolute and right: 4em to the button, and that helped push it over to the right, but when I give it a top value, it does it from the top of the page itself, so when I keep adding text to the input box and submitting it, all the buttons just pile on top of each other. I think I need to tell it to go from the top of the li, but I don't know how to do that. I also wanted to give the text in the li a max-width so that it wouldn't push the button down if there's a lot of text, but that doesn't seem to work.

**Comment by thomasjbradley** [comment]
`position: relative` is what you need.

The text can't push the button down if the button is using absolute.

**Comment by isabelle6** [comment]
I changed it to position: relative, and that fixed that issue, but now I think it's being relative to the text in the li, because it's sort of staggered on the right, depending on the length of the text.
![screen shot 2015-03-01 at 2 00 58 pm](https://cloud.githubusercontent.com/assets/6333962/6432341/6e17ad9c-c01b-11e4-829d-058be51c5ec7.png)

**Comment by thomasjbradley** [comment]
Are you positioning with `left` or `right`?

**Comment by isabelle6** [comment]
I tried both, and they both make the button stagger depending on the length of the text.

**Comment by thomasjbradley** [comment]
The `li` should be `position: relative`.
The `button` should be `position: absolute` and positioned using `right`.

---

I encourage you to go through the positioning videos again:
https://github.com/algonquindesign/html-css/tree/gh-pages/position-zindex

**Comment by isabelle6** [comment]
Ok, that worked. Thank you so much for all your help. I will definitely take a look at those videos again.
